description: >
  This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here.
  If you do not require an executor, you can simply delete this directory.
docker:
  - image: "pactfoundation/pact-cli:<<parameters.tag>>"
parameters:
  tag:
    default: latest
    description: >
      Pick a specific pact version to use:
      https://hub.docker.com/r/pactfoundation/pact-cli/tags/
    type: string
